services:
  camgiving-svc-ui:
    container_name: camgiving-svc-ui
    image: muyleangin/camgiving-nextjs:latest
    restart: always
    ports:
      - 3002:3000
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
    networks:
      - camgiving_net  

  cam-giving-service-api:
    container_name: cam-giving-service-api
    image: muyleangin/camgiving-api:latest
    environment:
      TZ: Asia/Bangkok
    ports:
      - '8001:8080'
    volumes:
      - '/home/camgiving/cam-giving-deployment/file-upload:/workspace/file-upload'
    networks:
      - camgiving_net  

  cam-giving-service-db:
    container_name: cam-giving-service-db
    image: postgres:14.7
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cam_giving
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - camgiving_net  

networks:
  camgiving_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.84.0.0/16
