services:
  photostad-service-ui:
    container_name: photostad-service-ui
    image: muyleangin/portistad-fontend-nextjs:latest
    restart: always
    ports:
      - 3004:3000
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
    networks:
      - photostad_net
  photostad-service-api:
    container_name: photostad-service-api
    image: muyleangin/photostad-svc-api:latest
    environment:
      TZ: Asia/Bangkok
    ports:
      - '8002:8080'
    volumes:
      - '/home/photostad/photostad-deployment-api/image:/workspace/image/'
      - '/home/photostad/photostad-deployment-api/excel:/workspace/excel/'
      - '/home/photostad/photostad-deployment-api/access-refresh-token-keys:/workspace/access-refresh-token-keys/'
      - '/home/photostad/photostad-deployment-api/image/font:/workspace/image/font/'
    networks:
      - photostad_net

  photostad-service-db:
    container_name: photostad-service-db
    image: postgres:14.8
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: photostad
      POSTGRES_PASSWORD: photostad4444
      POSTGRES_DB: photostad
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - photostad_net
networks:
  photostad_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.86.0.0/16