services:
  istademy-svc-ui:
    image: muyleangin/istademy-ui:latest
    restart: always
    ports:
      - 3006:3000
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
    networks:
      - istademy-network
networks:
  istademy-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.85.0.0/16