version: '3'
services:
  brachnha-svc-ui:
    image: muyleangin/brachnha-svc-ui:latest
    restart: always
    ports:
      - 3010:3000
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false