services:
  brachnha-svc-ui:
    image: muyleangin/brachnha-svc-ui:latest
    restart: always
    ports:
      - 3010:3000
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
    networks:
      - brachnha-network
networks:
  brachnha-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.82.0.0/16